"""Hermes Agent bridge — install from local clone, config, skill sync, launch."""

import os
import subprocess
import sys
from pathlib import Path

from . import config
from .helpers import write_ok, write_skip, write_info, write_fail, write_step


def _hermes_home() -> Path:
    if sys.platform == "win32":
        base = Path(os.environ.get("LOCALAPPDATA", ""))
        return (base / "hermes") if base else Path.home() / "AppData/Local/hermes"
    return Path.home() / ".hermes"


def _is_installed() -> bool:
    repo = config.HERMES_DIR
    venv = repo / ".venv" / "Scripts" / "hermes.exe" if sys.platform == "win32" else repo / ".venv" / "bin" / "hermes"
    return venv.exists()


def _hermes_cmd() -> str:
    repo = config.HERMES_DIR
    if sys.platform == "win32":
        return str(repo / ".venv" / "Scripts" / "hermes.exe")
    return str(repo / ".venv" / "bin" / "hermes")


def cmd_install() -> bool:
    if _is_installed():
        write_skip("Hermes Agent already installed")
        return True

    repo = config.HERMES_DIR
    if not repo.exists():
        write_fail(f"Clone Hermes Agent first: cd {config.ROOT_DIR} && git clone --filter=blob:none --depth 1 https://github.com/NousResearch/hermes-agent.git")
        return False

    write_step("HERMES", f"Installing from local clone ({repo})...")

    try:
        write_info("Creating venv and installing Hermes...")
        subprocess.run(
            [sys.executable, "-m", "venv", str(repo / ".venv")],
            check=True, capture_output=True, timeout=60,
        )

        pip = repo / ".venv" / "Scripts" / "pip.exe" if sys.platform == "win32" else repo / ".venv" / "bin" / "pip"
        subprocess.run(
            [str(pip), "install", "-e", str(repo)],
            check=True, capture_output=True, timeout=300,
        )

        write_ok(f"Hermes Agent installed from local clone")
        write_info(f"  Repo: {repo}")
        write_info(f"  Home: {_hermes_home()}")
        return True

    except subprocess.CalledProcessError as e:
        write_fail(f"Install failed: {e.stderr.decode()[:500] if e.stderr else str(e)}")
        return False
    except Exception as e:
        write_fail(f"Install failed: {e}")
        return False


def cmd_config() -> bool:
    hermes_home = _hermes_home()
    config_path = hermes_home / "config.yaml"
    config_path.parent.mkdir(parents=True, exist_ok=True)

    from .helpers import parse_api_key
    keys = parse_api_key()
    api_key = keys.api_key or os.environ.get("NINEROUTER_API_KEY", "")

    ecc_skills = str(config.ECC_DIR / "skills")
    data_skills = str(config.PROJECT_SKILLS_DIR)

    yaml = f"""# Hermes config — auto-generated by farewell-assistant v2
provider: openai
openai_base_url: http://localhost:20128/v1
openai_api_key: {api_key}

skills:
  external_dirs:
    - {ecc_skills}
    - {data_skills}

context:
  max_tokens: 8000
"""
    config_path.write_text(yaml, encoding="utf-8")
    write_ok(f"Config: {config_path}")
    write_info(f"Provider: 9Router (http://localhost:20128/v1)")
    write_info(f"Skills: {ecc_skills}")
    return True


def cmd_launch() -> bool:
    if not _is_installed():
        write_fail("Not installed. Run: fa hermes install")
        return False
    write_step("HERMES", "Starting Hermes Agent CLI...")
    try:
        subprocess.run([_hermes_cmd()])
        return True
    except Exception as e:
        write_fail(f"Launch failed: {e}")
        return False


def cmd_status() -> dict:
    hermes_home = _hermes_home()
    config_file = hermes_home / "config.yaml"
    skills_dir = hermes_home / "skills"

    write_step("HERMES", "Status")
    if _is_installed():
        write_ok(f"Installed (local clone: {config.HERMES_DIR})")
        write_info(f"  Home: {hermes_home}")
    else:
        write_skip("Not installed — run: fa hermes install")

    if config_file.exists():
        write_ok(f"Config: {config_file}")
    else:
        write_skip("No config — run: fa hermes config")

    skills_count = len(list(skills_dir.rglob("SKILL.md"))) if skills_dir.exists() else 0
    if skills_count > 0 or config.HERMES_DIR.exists():
        ecc_count = len(list((config.ECC_DIR / "skills").rglob("SKILL.md")))
        write_ok(f"ECC skills available: {ecc_count} (via external_dirs)")
    else:
        write_skip("No skills found")

    return {
        "installed": _is_installed(),
        "repo": str(config.HERMES_DIR),
        "home": str(hermes_home),
        "config_exists": config_file.exists(),
        "skills_count": skills_count,
    }


def main(action: str = "status"):
    actions = {"install": cmd_install, "config": cmd_config, "launch": cmd_launch, "status": cmd_status}
    fn = actions.get(action)
    if fn:
        fn()
    else:
        print(f"Unknown: {action}. Available: install, config, launch, status")
