"""Hermes Agent bridge — install, config, skill sync, launch."""

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

from . import config
from .helpers import _c, write_ok, write_skip, write_info, write_fail, write_step


def _hermes_home() -> Path:
    if sys.platform == "win32":
        base = Path(os.environ.get("LOCALAPPDATA", ""))
        return base / "hermes" if base else Path.home() / "AppData/Local/hermes"
    return Path.home() / ".hermes"


def _is_installed() -> bool:
    return shutil.which("hermes") is not None or (_hermes_home() / "bin").exists()


def _hermes_env() -> dict:
    env = dict(os.environ)
    hermes_bin = _hermes_home() / "bin"
    if hermes_bin.exists():
        env["PATH"] = str(hermes_bin) + os.pathsep + env.get("PATH", "")
    return env


def cmd_install() -> bool:
    """Install Hermes Agent via the official installer."""
    if _is_installed():
        write_skip("Hermes Agent already installed")
        return True

    write_step("HERMES", "Installing Hermes Agent...")
    if sys.platform == "win32":
        cmd = ['powershell', '-NoProfile', '-Command',
               'iex (irm https://hermes-agent.nousresearch.com/install.ps1)']
    else:
        cmd = ['bash', '-c', 'curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash']

    try:
        r = subprocess.run(cmd, timeout=300)
        if r.returncode != 0:
            write_fail("Hermes install failed")
            return False
        write_ok("Hermes Agent installed")
        return True
    except Exception as e:
        write_fail(f"Hermes install failed: {e}")
        return False


def cmd_config() -> bool:
    """Write Hermes config.yaml pointing to 9Router + ECC external skills."""
    hermes_home = _hermes_home()
    config_path = hermes_home / "config.yaml"
    config_path.parent.mkdir(parents=True, exist_ok=True)

    from .helpers import parse_api_key
    keys = parse_api_key()
    api_key = keys.api_key or os.environ.get("NINEROUTER_API_KEY", "")

    # Map ECC skills as external dir (no conversion needed)
    ecc_skills = str(config.ECC_DIR / "skills")
    data_skills = str(config.PROJECT_SKILLS_DIR)

    yaml_content = f"""# Hermes config — auto-generated by farewell-assistant v2
provider: openai
openai_base_url: http://localhost:20128/v1
openai_api_key: {api_key}

skills:
  external_dirs:
    - {ecc_skills}
    - {data_skills}

context:
  max_tokens: 8000
"""
    config_path.write_text(yaml_content, encoding="utf-8")
    write_ok(f"Hermes config written to {config_path}")
    write_info(f"Provider: 9Router (http://localhost:20128/v1)")
    write_info(f"External skills: {ecc_skills}")
    return True


def cmd_sync_skills() -> bool:
    """Symlink ECC skills into Hermes skills dir for direct discovery."""
    hermes_skills = _hermes_home() / "skills"
    hermes_skills.mkdir(parents=True, exist_ok=True)

    # Option A: Create a junction/symlink to ecc/skills
    ecc_link = hermes_skills / "ecc"
    if not ecc_link.exists():
        try:
            if sys.platform == "win32":
                r = subprocess.run(
                    ["cmd", "/c", "mklink", "/J", str(ecc_link), str(config.ECC_DIR / "skills")],
                    capture_output=True, text=True, timeout=10,
                )
                ok = r.returncode == 0
            else:
                ecc_link.symlink_to(config.ECC_DIR / "skills", target_is_directory=True)
                ok = True
        except Exception:
            ok = False
        if ok:
            write_ok(f"ECC skills linked to {ecc_link}")
        else:
            # Fallback: use external_dirs in config instead
            write_skip("Symlink failed, using external_dirs config instead")
            return cmd_config()
    else:
        write_skip("ECC skills already linked")

    return True


def cmd_launch() -> bool:
    """Launch Hermes Agent CLI or gateway."""
    if not _is_installed():
        write_fail("Hermes Agent not installed. Run: py -m farewell_assistant hermes install")
        return False

    env = _hermes_env()
    write_step("HERMES", "Starting Hermes Agent CLI...")
    try:
        subprocess.run(["hermes"], env=env)
        return True
    except Exception as e:
        write_fail(f"Hermes launch failed: {e}")
        return False


def cmd_status() -> dict:
    """Check Hermes Agent installation status."""
    installed = _is_installed()
    hermes_home = _hermes_home()
    config_file = hermes_home / "config.yaml"
    skills_dir = hermes_home / "skills"

    result = {
        "installed": installed,
        "home": str(hermes_home),
        "config_exists": config_file.exists(),
        "skills_count": len(list(skills_dir.rglob("SKILL.md"))) if skills_dir.exists() else 0,
    }

    write_step("HERMES", "Status")
    if installed:
        write_ok(f"Installed at {hermes_home}")
    else:
        write_skip("Not installed — run: fa hermes install")

    if config_file.exists():
        write_ok(f"Config: {config_file}")
    else:
        write_skip("No Hermes config yet")

    if result["skills_count"] > 0:
        write_ok(f"Skills: {result['skills_count']} SKILL.md files")
    else:
        write_skip("No Hermes skills found")

    return result


def main(action: str = "status"):
    actions = {
        "install": cmd_install,
        "config": cmd_config,
        "sync-skills": cmd_sync_skills,
        "launch": cmd_launch,
        "status": cmd_status,
    }
    fn = actions.get(action)
    if fn:
        fn()
    else:
        print(f"Unknown hermes action: {action}")
        print("Available: install, config, sync-skills, launch, status")
